baseURL = "https://blog.kylelanchman.com"
languageCode = "en-us"
title = "Kyle Lanchman"
theme = "beautifulhugo"

[markup]
  [markup.highlight]
    noclasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:title"

[params]
  subtitle = "Rambling about tech and weeb stuff"
  favicon = "/img/icon.png"
  logo = "/img/logo.png"
  wordCount = true
  readingTime = true
  showRelatedPosts = true

[author]
  name = "Kyle Lanchman"
  website = "https://kylelanchman.com"
  email = "blog@kylelanchman.com"
  github = "klanchman"
  mastodon = "mstdn.io/@klanchman"
  # Included for completeness, but...
  # twitter = "klanchman"

[taxonomies]
  # category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 1

[[menu.main]]
  name = "Series"
  url = "series"
  weight = 2

[[menu.main]]
  name = "Feeds"
  weight = 10

[[menu.main]]
  name = "JSON"
  url = "feed.json"
  weight = 11
  parent = "Feeds"

[[menu.main]]
  name = "RSS"
  url = "index.xml"
  weight = 12
  parent = "Feeds"

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true
  permalinkable = true

[outputs]
  home = ["html", "jsonfeed", "rss"]
